/**
 * Static note catalog — loads note metadata for wikilink resolution.
 *
 * Primary source: pre-built `notes-index.json` (generated by `pnpm sync`).
 * This avoids walking + parsing the entire obsidian directory at remark compile time.
 *
 * Fallback: FS walk + the shared full-YAML frontmatter adapter for custom
 * roots used by tooling/tests; it does not maintain a second parser.
 */

import type { NotesIndex } from '../../types/knowledge-index';
import { buildSlugMap, resolveWikilinkTarget } from './slug-resolver';

// Static import — Vite/Astro inlines this at build time.
// If the file doesn't exist, the build will error (run `pnpm sync` first).
import notesIndexData from '../../data/indexes/notes-index.json';

interface StaticCatalogEntry {
  id: string;
  data: {
    title?: string | null;
    aliases?: string[] | null;
    draft?: boolean | null;
    private?: boolean | null;
    visibility?: string | null;
    asset_id?: string | null;
    asset_type?: 'service' | 'tool' | 'host' | 'network' | 'subscription' | 'project' | null;
  };
}

interface StaticCatalogCache {
  entries: StaticCatalogEntry[];
  slugMap: ReturnType<typeof buildSlugMap>;
}

let catalogCache: StaticCatalogCache | null = null;

/**
 * Build catalog entries from the pre-built notes index.
 * This is the fast path — no FS walk, no frontmatter parsing.
 */
function buildFromIndex(): StaticCatalogCache {
  const indexData = notesIndexData as unknown as NotesIndex;
  const entries: StaticCatalogEntry[] = indexData.entries.map(e => ({
    id: e.id,
    data: {
      title: e.title ?? null,
      aliases: e.aliases ?? null,
      draft: e.draft ?? null,
      private: e.private ?? null,
      visibility: e.visibility ?? null,
      asset_id: e.asset_id ?? null,
      asset_type: e.asset_type ?? null,
    },
  }));
  return { entries, slugMap: buildSlugMap(entries) };
}

// ── Fallback: FS walk + shared full-YAML adapter ──

import fs from 'node:fs';
import path from 'node:path';
import { toNoteId } from '../foundation/note-id';
import {
  frontmatterBoolean,
  frontmatterString,
  frontmatterStringArray,
  parseMarkdownFrontmatter,
} from '../markdown/frontmatter';

function walkMarkdown(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];

  const results: string[] = [];
  for (const entry of fs.readdirSync(dir)) {
    if (entry.startsWith('.')) continue;
    const fullPath = path.join(dir, entry);
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      results.push(...walkMarkdown(fullPath));
    } else if (entry.endsWith('.md')) {
      results.push(fullPath);
    }
  }
  return results;
}

type CatalogAssetType = NonNullable<StaticCatalogEntry['data']['asset_type']>;
const ASSET_TYPES = new Set<CatalogAssetType>([
  'service',
  'tool',
  'host',
  'network',
  'subscription',
  'project',
]);

function isCatalogAssetType(value: string | undefined): value is CatalogAssetType {
  return value !== undefined && ASSET_TYPES.has(value as CatalogAssetType);
}

function parseCatalogEntry(filePath: string, notesRoot: string): StaticCatalogEntry {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const relativePath = path.relative(notesRoot, filePath).replace(/\\/g, '/');
  const { data } = parseMarkdownFrontmatter(raw, relativePath);
  const assetType = frontmatterString(data.asset_type);

  return {
    id: toNoteId(relativePath),
    data: {
      title: frontmatterString(data.title) ?? null,
      aliases: frontmatterStringArray(data.aliases),
      draft: data.draft == null ? null : frontmatterBoolean(data.draft),
      private: data.private == null ? null : frontmatterBoolean(data.private),
      visibility: frontmatterString(data.visibility) ?? null,
      asset_id: frontmatterString(data.asset_id) ?? null,
      asset_type: isCatalogAssetType(assetType) ? assetType : null,
    },
  };
}

function buildFromFS(notesRoot: string): StaticCatalogCache {
  const entries = walkMarkdown(notesRoot).map(filePath => parseCatalogEntry(filePath, notesRoot));
  return { entries, slugMap: buildSlugMap(entries) };
}

// ── Public API ──

/**
 * Load the static note catalog for wikilink resolution.
 *
 * Default: reads from pre-built `notes-index.json` (fast, no FS walk).
 * With custom notesRoot: falls back to FS walk + the shared YAML adapter.
 */
export function loadStaticNoteCatalog(notesRoot?: string): StaticCatalogCache {
  if (catalogCache) return catalogCache;

  if (!notesRoot) {
    // Fast path: use pre-built index
    catalogCache = buildFromIndex();
    return catalogCache;
  }

  // Fallback: FS walk (only when custom root is specified)
  const resolvedRoot = path.resolve(notesRoot);
  catalogCache = buildFromFS(resolvedRoot);
  return catalogCache;
}

export function resolveStaticWikilink(target: string, notesRoot?: string) {
  const catalog = loadStaticNoteCatalog(notesRoot);
  return resolveWikilinkTarget(target, catalog.slugMap, catalog.entries);
}
