/**
 * Static note catalog — loads note metadata for wikilink resolution.
 *
 * Primary source: pre-built `notes-index.json` (generated by `pnpm sync`).
 * This avoids walking + parsing the entire obsidian directory at remark compile time.
 *
 * Fallback: FS walk + frontmatter parse (for environments where the index
 * is not yet available, e.g., first build before sync).
 */

import type { NotesIndex } from '../../types/knowledge-index';
import { buildSlugMap, resolveWikilinkTarget } from './slug-resolver';

// Static import — Vite/Astro inlines this at build time.
// If the file doesn't exist, the build will error (run `pnpm sync` first).
import notesIndexData from '../../data/indexes/notes-index.json';

interface StaticCatalogEntry {
  id: string;
  data: {
    title?: string | null;
    aliases?: string[] | null;
    draft?: boolean | null;
    private?: boolean | null;
    visibility?: string | null;
    asset_id?: string | null;
    asset_type?: 'service' | 'tool' | 'host' | 'network' | null;
  };
}

interface StaticCatalogCache {
  entries: StaticCatalogEntry[];
  slugMap: ReturnType<typeof buildSlugMap>;
}

let catalogCache: StaticCatalogCache | null = null;

/**
 * Build catalog entries from the pre-built notes index.
 * This is the fast path — no FS walk, no frontmatter parsing.
 */
function buildFromIndex(): StaticCatalogCache {
  const indexData = notesIndexData as unknown as NotesIndex;
  const entries: StaticCatalogEntry[] = indexData.entries.map(e => ({
    id: e.id,
    data: {
      title: e.title ?? null,
      aliases: e.aliases ?? null,
      draft: e.draft ?? null,
      private: e.private ?? null,
      visibility: e.visibility ?? null,
      asset_id: e.asset_id ?? null,
      asset_type: e.asset_type ?? null,
    },
  }));
  return { entries, slugMap: buildSlugMap(entries) };
}

// ── Fallback: FS walk + frontmatter parse ──

import fs from 'node:fs';
import path from 'node:path';
import { toNoteId } from '../foundation/note-id';

function walkMarkdown(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];

  const results: string[] = [];
  for (const entry of fs.readdirSync(dir)) {
    if (entry.startsWith('.')) continue;
    const fullPath = path.join(dir, entry);
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      results.push(...walkMarkdown(fullPath));
    } else if (entry.endsWith('.md')) {
      results.push(fullPath);
    }
  }
  return results;
}

function parseInlineList(rawValue: string): string[] {
  const value = rawValue.trim();
  if (!value.startsWith('[') || !value.endsWith(']')) {
    const item = value.replace(/^['"]|['"]$/g, '').trim();
    return item ? [item] : [];
  }

  const inner = value.slice(1, -1).trim();
  if (!inner) return [];

  const items: string[] = [];
  let current = '';
  let quote: '"' | "'" | null = null;

  for (const char of inner) {
    if (quote) {
      current += char;
      if (char === quote) {
        quote = null;
      }
      continue;
    }

    if (char === '"' || char === "'") {
      quote = char;
      current += char;
      continue;
    }

    if (char === ',') {
      const item = current.trim().replace(/^['"]|['"]$/g, '');
      if (item) items.push(item);
      current = '';
      continue;
    }

    current += char;
  }

  const tail = current.trim().replace(/^['"]|['"]$/g, '');
  if (tail) items.push(tail);
  return items;
}

function parseBooleanish(rawValue: string | undefined): boolean | null {
  if (!rawValue) return null;
  const value = rawValue.trim().toLowerCase();
  if (value === 'true') return true;
  if (value === 'false') return false;
  return null;
}

function extractFrontmatter(text: string): string | null {
  if (!text.startsWith('---')) return null;
  const lines = text.split('\n');
  let closingIndex = -1;
  for (let index = 1; index < lines.length; index++) {
    if (lines[index].trim() === '---') {
      closingIndex = index;
      break;
    }
  }
  if (closingIndex === -1) return null;
  return lines.slice(1, closingIndex).join('\n');
}

function parseCatalogEntry(filePath: string, notesRoot: string): StaticCatalogEntry {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const frontmatter = extractFrontmatter(raw);
  const relativePath = path.relative(notesRoot, filePath).replace(/\\/g, '/');
  const entry: StaticCatalogEntry = {
    id: toNoteId(relativePath),
    data: {
      aliases: [],
    },
  };

  if (!frontmatter) {
    return entry;
  }

  const lines = frontmatter.split('\n');
  let currentKey: 'aliases' | null = null;

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    if (currentKey && line.trimStart().startsWith('- ')) {
      const alias = line.trimStart().slice(2).trim().replace(/^['"]|['"]$/g, '');
      if (alias) {
        entry.data.aliases = [...(entry.data.aliases ?? []), alias];
      }
      continue;
    }

    currentKey = null;
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$/);
    if (!match) continue;

    const [, key, rawValue] = match;
    const value = rawValue.trim();

    switch (key) {
      case 'title':
        entry.data.title = value.replace(/^['"]|['"]$/g, '') || null;
        break;
      case 'aliases':
        if (!value) {
          currentKey = 'aliases';
          entry.data.aliases = entry.data.aliases ?? [];
        } else {
          entry.data.aliases = parseInlineList(value);
        }
        break;
      case 'draft':
        entry.data.draft = parseBooleanish(value);
        break;
      case 'private':
        entry.data.private = parseBooleanish(value);
        break;
      case 'visibility':
        entry.data.visibility = value.replace(/^['"]|['"]$/g, '') || null;
        break;
      case 'asset_id':
        entry.data.asset_id = value.replace(/^['"]|['"]$/g, '') || null;
        break;
      case 'asset_type': {
        const assetType = value.replace(/^['"]|['"]$/g, '');
        if (assetType === 'service' || assetType === 'tool' || assetType === 'host' || assetType === 'network') {
          entry.data.asset_type = assetType;
        }
        break;
      }
      default:
        break;
    }
  }

  return entry;
}

function buildFromFS(notesRoot: string): StaticCatalogCache {
  const entries = walkMarkdown(notesRoot).map(filePath => parseCatalogEntry(filePath, notesRoot));
  return { entries, slugMap: buildSlugMap(entries) };
}

// ── Public API ──

/**
 * Load the static note catalog for wikilink resolution.
 *
 * Default: reads from pre-built `notes-index.json` (fast, no FS walk).
 * With custom notesRoot: falls back to FS walk + frontmatter parse.
 */
export function loadStaticNoteCatalog(notesRoot?: string): StaticCatalogCache {
  if (catalogCache) return catalogCache;

  if (!notesRoot) {
    // Fast path: use pre-built index
    catalogCache = buildFromIndex();
    return catalogCache;
  }

  // Fallback: FS walk (only when custom root is specified)
  const resolvedRoot = path.resolve(notesRoot);
  catalogCache = buildFromFS(resolvedRoot);
  return catalogCache;
}

export function resolveStaticWikilink(target: string, notesRoot?: string) {
  const catalog = loadStaticNoteCatalog(notesRoot);
  return resolveWikilinkTarget(target, catalog.slugMap, catalog.entries);
}
