/**
 * Asset index merger — enriches locally-generated asset-index.json
 * with structured fields from the upstream knowledge-index.
 *
 * Problem: `build-indexes.ts` parses frontmatter with a line-by-line regex
 * scanner that cannot handle multi-line YAML block scalars. Fields like
 * `monitor` (nested object) and `links` (array of objects) are silently
 * dropped, causing asset detail pages to show "[ NO_SIGNAL ]".
 *
 * Solution: The upstream `thought-forest/generated/knowledge-index/asset-index.json`
 * is generated by `kb:index` (which uses gray-matter for full YAML parsing) and
 * already contains these fields correctly. After `buildIndexes()` generates the
 * local asset-index with correct note-level metadata (title, tags, visibility…),
 * this module reads the upstream file and overlays the asset-specific nested
 * fields, then writes the merged result back.
 *
 * Field mapping (upstream camelCase → local snake_case):
 *   assetId         → asset_id       (join key)
 *   monitor         → monitor        (nested object)
 *   links           → links          (array of link objects)
 *   homepage        → homepage       (homepage config object)
 *   assetRole       → asset_role
 *   hostAssetId     → host_asset_id
 *   parentAssetId   → parent_asset_id
 *   status          → status
 */

import fs from 'node:fs';
import path from 'node:path';

// ── Upstream asset-index types (matches thought-forest/scripts/knowledge-index/types.ts) ──

interface UpstreamAssetLink {
  label: string;
  url: string;
  kind?: string;
  visibility?: 'public' | 'internal';
}

interface UpstreamMonitorConfig {
  provider?: 'nezha' | 'uptime-kuma' | 'none';
  url?: string;
  target_id?: string;
  label?: string;
}

interface UpstreamHomepage {
  enabled: boolean;
  section?: 'services' | 'projects' | 'tools';
  featured: boolean;
  order: number;
}

interface UpstreamAssetItem {
  assetId: string;
  assetType: string;
  sourceId: string;
  title: string;
  visibility: string;
  status?: string;
  assetRole?: string;
  hostAssetId?: string;
  parentAssetId?: string;
  homepage?: UpstreamHomepage;
  monitor?: UpstreamMonitorConfig;
  links?: UpstreamAssetLink[];
}

/**
 * Merge upstream asset-index.json fields into the locally-generated asset-index.json.
 *
 * @param knowledgeIndexDir - Absolute path to the upstream knowledge-index directory
 *                            (e.g. `/home/thought-forest/generated/knowledge-index`)
 * @param indexDir          - Absolute path to the local indexes output directory
 *                            (e.g. `/projects/digital-biome/src/data/indexes`)
 */
export function mergeAssetIndex(knowledgeIndexDir: string, indexDir: string): void {
  const upstreamPath = path.join(knowledgeIndexDir, 'asset-index.json');
  const localPath = path.join(indexDir, 'asset-index.json');

  if (!fs.existsSync(upstreamPath)) {
    console.log(`  [merge-asset-index] Upstream not found at ${upstreamPath} — skipping`);
    return;
  }

  if (!fs.existsSync(localPath)) {
    console.log(`  [merge-asset-index] Local asset-index not found at ${localPath} — skipping`);
    return;
  }

  let upstream: UpstreamAssetItem[];
  let local: { version: number; generatedAt: string; entries: Record<string, unknown>[] };

  try {
    upstream = JSON.parse(fs.readFileSync(upstreamPath, 'utf-8'));
  } catch (e) {
    console.warn(`  [merge-asset-index] Failed to parse upstream asset-index: ${e}`);
    return;
  }

  try {
    local = JSON.parse(fs.readFileSync(localPath, 'utf-8'));
  } catch (e) {
    console.warn(`  [merge-asset-index] Failed to parse local asset-index: ${e}`);
    return;
  }

  // Build lookup table: upstream assetId → upstream entry
  const upstreamById = new Map<string, UpstreamAssetItem>(
    upstream.map(item => [item.assetId, item])
  );

  let mergedCount = 0;
  let missingCount = 0;

  const mergedEntries = local.entries.map(entry => {
    const assetId = entry['asset_id'] as string | undefined;
    if (!assetId) return entry;

    const upstreamEntry = upstreamById.get(assetId);
    if (!upstreamEntry) {
      missingCount++;
      return entry;
    }

    mergedCount++;

    // Build merged entry: local fields take precedence for note metadata;
    // upstream fields fill in nested asset-specific data that the local
    // line-by-line YAML scanner cannot parse.
    const merged: Record<string, unknown> = { ...entry };

    // Overlay monitor (nested object)
    if (upstreamEntry.monitor !== undefined) {
      merged['monitor'] = upstreamEntry.monitor;
    }

    // Overlay links (array of objects)
    if (upstreamEntry.links !== undefined && upstreamEntry.links.length > 0) {
      merged['links'] = upstreamEntry.links;
    }

    // Overlay homepage (homepage config object)
    if (upstreamEntry.homepage !== undefined) {
      merged['homepage'] = upstreamEntry.homepage;
    }

    // Overlay asset_role (camelCase → snake_case)
    if (upstreamEntry.assetRole !== undefined) {
      merged['asset_role'] = upstreamEntry.assetRole;
    }

    // Overlay host_asset_id
    if (upstreamEntry.hostAssetId !== undefined) {
      merged['host_asset_id'] = upstreamEntry.hostAssetId;
    }

    // Overlay parent_asset_id
    if (upstreamEntry.parentAssetId !== undefined) {
      merged['parent_asset_id'] = upstreamEntry.parentAssetId;
    }

    // Overlay status (upstream may be more authoritative, but don't overwrite if local has it)
    if (upstreamEntry.status !== undefined && !entry['status']) {
      merged['status'] = upstreamEntry.status;
    }

    return merged;
  });

  const result = { ...local, entries: mergedEntries };
  fs.writeFileSync(localPath, JSON.stringify(result, null, 2), 'utf-8');

  console.log(
    `  [merge-asset-index] Merged ${mergedCount} assets from upstream` +
    (missingCount > 0 ? ` (${missingCount} local assets not found in upstream)` : '')
  );
}
