/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 564987d31c4bacf6c28a69e56ed5e49c)
interface __BaseEnv_Env {
	CF_ACCESS_TEAM_DOMAIN: string;
	CF_ACCESS_AUD: string;
	PRIVATE_INFRASTRUCTURE_JSON: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "PRIVATE_INFRASTRUCTURE_JSON">> {}
}
