/**
 * Knowledge index loader — static imports for pre-built JSON indexes.
 *
 * These indexes are generated by `scripts/sync/build-indexes.ts` during
 * `pnpm sync` and live in `src/data/indexes/`. Astro/Vite inlines
 * JSON imports at build time, so there is no runtime file I/O.
 */

import type {
  NotesIndex,
  NoteIndexEntry,
  LinkGraphIndex,
  TagIndex,
  AssetIndex,
  AssetIndexEntry,
} from '../types/knowledge-index';
import { VISIBILITY_PRIVATE } from '../domain/constants';

import notesIndexData from '../data/indexes/notes-index.json';
import linkGraphIndexData from '../data/indexes/link-graph.json';
import tagIndexData from '../data/indexes/tag-index.json';
import assetIndexData from '../data/indexes/asset-index.json';

// ── Raw index access ──
// JSON default imports have a narrow inferred type that doesn't always
// satisfy the full interface (e.g. optional fields may be absent in the
// JSON but required in the interface). A single `as` cast is used here;
// the JSON structure is guaranteed by `scripts/sync/build-indexes.ts`.

export function getNotesIndex(): NotesIndex {
  return notesIndexData as NotesIndex;
}

export function getLinkGraphIndex(): LinkGraphIndex {
  return linkGraphIndexData as LinkGraphIndex;
}

export function getTagIndex(): TagIndex {
  return tagIndexData as TagIndex;
}

export function getAssetIndex(): AssetIndex {
  return assetIndexData as AssetIndex;
}

// ── Derived accessors ──

/** All note index entries. */
export function getAllNoteEntries(): NoteIndexEntry[] {
  return getNotesIndex().entries;
}

// ── Lookup caches (built once, reused) ──

let noteEntryByIdCache: Map<string, NoteIndexEntry> | null = null;

function getNoteEntryByIdMap(): Map<string, NoteIndexEntry> {
  if (noteEntryByIdCache) return noteEntryByIdCache;
  const map = new Map<string, NoteIndexEntry>();
  for (const entry of getAllNoteEntries()) {
    map.set(entry.id, entry);
  }
  noteEntryByIdCache = map;
  return map;
}

let publicKnowledgeEntriesCache: NoteIndexEntry[] | null = null;

/** Note id prefix for config/operational documents that must never appear in public content. */
const CONFIG_PATH_PREFIX = 'obsidian/config/';

/** Public, non-draft, non-private knowledge note entries. */
export function getPublicKnowledgeNoteEntriesFromIndex(): NoteIndexEntry[] {
  if (publicKnowledgeEntriesCache) return publicKnowledgeEntriesCache;
  const result = getAllNoteEntries().filter(
    e =>
      !e.isAsset &&
      !e.draft &&
      !e.private &&
      e.visibility !== VISIBILITY_PRIVATE &&
      // Exclude operational/config documents (skills, AGENTS.md, etc.) that are
      // synced from thought-forest/config/ but must not appear as public content.
      !e.id.startsWith(CONFIG_PATH_PREFIX)
  );
  publicKnowledgeEntriesCache = result;
  return result;
}

/** Public asset entries. */
let publicAssetEntriesCache: AssetIndexEntry[] | null = null;

export function getPublicAssetEntriesFromIndex(): AssetIndexEntry[] {
  if (publicAssetEntriesCache) return publicAssetEntriesCache;
  const result = getAssetIndex().entries.filter(
    e => !e.draft && !e.private && e.visibility !== VISIBILITY_PRIVATE
  );
  publicAssetEntriesCache = result;
  return result;
}

/** Find a single note entry by id. O(1) via cached Map. */
export function getNoteEntryByIdFromIndex(id: string): NoteIndexEntry | undefined {
  return getNoteEntryByIdMap().get(id);
}

/** Tag counts (public notes only, pre-sorted by count desc). */
export function getTagCountsFromIndex(): Array<{ tag: string; count: number }> {
  return getTagIndex().tags;
}

/** Count of public knowledge notes (non-asset, non-draft, non-private). */
export function getPublicNotesCountFromIndex(): number {
  return getPublicKnowledgeNoteEntriesFromIndex().length;
}

/**
 * Build a backlinks map from the link graph.
 * Returns a Map<targetId, sourceId[]> — who links TO each note.
 */
let backlinksCache: Map<string, string[]> | null = null;

export function getBacklinksMapFromIndex(): Map<string, string[]> {
  if (backlinksCache) return backlinksCache;

  const graph = getLinkGraphIndex();
  const map = new Map<string, string[]>();

  for (const entry of graph.entries) {
    for (const targetId of entry.outgoingIds) {
      const existing = map.get(targetId);
      if (existing) {
        existing.push(entry.sourceId);
      } else {
        map.set(targetId, [entry.sourceId]);
      }
    }
  }

  backlinksCache = map;
  return map;
}

/**
 * Build an outgoing links map from the link graph.
 * Returns a Map<sourceId, targetId[]>.
 */
let outgoingCache: Map<string, string[]> | null = null;

export function getOutgoingMapFromIndex(): Map<string, string[]> {
  if (outgoingCache) return outgoingCache;

  const graph = getLinkGraphIndex();
  const map = new Map<string, string[]>();

  for (const entry of graph.entries) {
    map.set(entry.sourceId, entry.outgoingIds);
  }

  outgoingCache = map;
  return map;
}
