/**
 * Export PRIVATE_INFRASTRUCTURE_JSON from upstream asset-index.
 *
 * Usage:
 *   pnpm export:private
 *   pnpm export:private -- --out .dev.vars.private.json
 *   pnpm export:private -- --print
 *
 * Values are derived from protected asset links + HostName/IP fields.
 * Showcase UI aliases (vps.*.ip, portal.home) are included for unlock compatibility.
 */
import fs from 'node:fs';
import path from 'node:path';
import { notesConfig } from '../notes.config';
import { buildPrivateLinkRefs } from '../edge/private-refs';
import { parsePrivateInfrastructure } from '../edge/private-infrastructure';

interface UpstreamAssetLink {
  label: string;
  url: string;
  kind?: string;
  visibility?: 'public' | 'private' | 'internal';
}

interface UpstreamAssetItem {
  assetId: string;
  links?: UpstreamAssetLink[];
}

const FULL_IPV4 =
  /(?<![\d.])(?:25[0-5]|2[0-4]\d|1?\d?\d)(?:\.(?:25[0-5]|2[0-4]\d|1?\d?\d)){3}(?![\d.])/g;

/** Showcase aliases kept for InfrastructureShowcase private_ref keys. */
const SHOWCASE_IP_ALIASES: Record<string, string> = {
  'vps.azure-hk.ip': 'host-azure-hk-vps',
  'vps.aliyun-chengdu.ip': 'host-aliyun-chengdu-dailyuse-vps',
  'vps.azure-japan.ip': 'host-azure-japan-singbox-vps',
  'vps.azure-korea.ip': 'host-azure-korea-singbox-vps',
};

const PORTAL_HOME_CANDIDATES = [
  'svc-homepage-dashboard.links.app',
  'host-debian-services-vm.links.app.homepage',
  'host-n100-pve.links.admin',
];

function extractIpv4(value: string): string | null {
  const match = value.match(FULL_IPV4);
  return match?.[0] ?? null;
}

function extractHostnameIp(url: string): string | null {
  try {
    const parsed = new URL(url);
    if (FULL_IPV4.test(parsed.hostname)) {
      // reset lastIndex side effect from /g
      FULL_IPV4.lastIndex = 0;
      return parsed.hostname;
    }
  } catch {
    // ignore invalid URLs
  }
  FULL_IPV4.lastIndex = 0;
  return extractIpv4(url);
}

function loadUpstreamAssets(): UpstreamAssetItem[] {
  const upstreamPath = path.resolve(
    process.cwd(),
    notesConfig.upstream.generatedPath,
    'knowledge-index',
    'asset-index.json',
  );
  if (!fs.existsSync(upstreamPath)) {
    throw new Error(
      `Upstream asset-index not found at ${upstreamPath}. Run kb:index in thought-forest or set NOTES_UPSTREAM_GENERATED.`,
    );
  }
  const parsed: unknown = JSON.parse(fs.readFileSync(upstreamPath, 'utf8'));
  if (!Array.isArray(parsed)) {
    throw new Error('Upstream asset-index must be an array.');
  }
  return parsed as UpstreamAssetItem[];
}

export function buildPrivateInfrastructurePayload(assets: UpstreamAssetItem[]) {
  const values: Record<string, string> = {};
  const links: Record<string, string> = {};
  const ipByAsset = new Map<string, string>();

  for (const asset of assets) {
    const assetLinks = asset.links ?? [];
    for (const { link, privateRef } of buildPrivateLinkRefs(asset.assetId, assetLinks)) {
      if (!privateRef || !link.url) continue;
      links[privateRef] = link.url.trim();
      const ip = extractHostnameIp(link.url);
      if (ip && !ipByAsset.has(asset.assetId)) {
        ipByAsset.set(asset.assetId, ip);
      }
    }
  }

  for (const [assetId, ip] of ipByAsset) {
    values[`${assetId}.ip`] = ip;
  }

  for (const [alias, assetId] of Object.entries(SHOWCASE_IP_ALIASES)) {
    const ip = ipByAsset.get(assetId);
    if (ip) values[alias] = ip;
  }

  for (const candidate of PORTAL_HOME_CANDIDATES) {
    if (links[candidate]) {
      links['portal.home'] = links[candidate];
      break;
    }
  }

  return {
    version: 1 as const,
    values,
    links,
  };
}

function parseArgs(argv: string[]) {
  const outIndex = argv.indexOf('--out');
  const outPath = outIndex >= 0 ? argv[outIndex + 1] : null;
  const printOnly = argv.includes('--print');
  const asDevVars = argv.includes('--dev-vars');
  return { outPath, printOnly, asDevVars };
}

function main() {
  const { outPath, printOnly, asDevVars } = parseArgs(process.argv.slice(2));
  const payload = buildPrivateInfrastructurePayload(loadUpstreamAssets());
  // Validate against runtime parser before writing.
  parsePrivateInfrastructure(JSON.stringify(payload));

  const json = JSON.stringify(payload);
  const pretty = JSON.stringify(payload, null, 2);

  if (printOnly) {
    process.stdout.write(`${pretty}\n`);
    return;
  }

  if (asDevVars) {
    const content = [
      '# Generated by pnpm export:private -- --dev-vars',
      '# Fill CF_ACCESS_* for local Pages Functions emulation with wrangler pages dev.',
      'CF_ACCESS_TEAM_DOMAIN=example.cloudflareaccess.com',
      'CF_ACCESS_AUD=0000000000000000000000000000000000000000000000000000000000000000',
      `PRIVATE_INFRASTRUCTURE_JSON=${json}`,
      '',
    ].join('\n');
    const target = outPath || '.dev.vars';
    fs.writeFileSync(target, content, 'utf8');
    console.log(`Wrote ${target} (${Object.keys(payload.values).length} values, ${Object.keys(payload.links).length} links)`);
    return;
  }

  const target = outPath || path.join('tmp', 'private-infrastructure.json');
  fs.mkdirSync(path.dirname(path.resolve(target)), { recursive: true });
  fs.writeFileSync(target, `${pretty}\n`, 'utf8');
  console.log(`Wrote ${target} (${Object.keys(payload.values).length} values, ${Object.keys(payload.links).length} links)`);
  console.log('Set Cloudflare secret PRIVATE_INFRASTRUCTURE_JSON to the minified JSON (or use the file contents).');
}

main();
