/**
 * Render PRIVATE_INFRASTRUCTURE_JSON from the producer-owned Personal Infrastructure runtime binding.
 *
 * Usage:
 *   pnpm export:private -- --contract <binding.json>
 *   pnpm export:private -- --contract <binding.json> --out tmp/private-infrastructure.json
 *   pnpm export:private -- --contract <binding.json> --print
 */
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import {
  parsePrivateInfrastructure,
  type PrivateInfrastructurePayload,
} from '../edge/private-infrastructure';

export const DEFAULT_PRIVATE_INFRASTRUCTURE_BINDING =
  '.pds-runtime/personal-infrastructure/bindings/digital-biome/private-infrastructure-v1.json';

function assertRecord(value: unknown, label: string): asserts value is Record<string, unknown> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${label} must be an object`);
  }
}

function assertExactKeys(value: Record<string, unknown>, expected: string[], label: string): void {
  const actual = Object.keys(value).sort();
  const wanted = [...expected].sort();
  if (actual.length !== wanted.length || actual.some((key, index) => key !== wanted[index])) {
    throw new Error(
      `${label} fields mismatch: expected ${wanted.join(', ')}; got ${actual.join(', ')}`,
    );
  }
}

export function parsePrivateInfrastructureBinding(raw: string): PrivateInfrastructurePayload {
  const value: unknown = JSON.parse(raw);
  assertRecord(value, 'private infrastructure binding');
  assertExactKeys(
    value,
    ['apiVersion', 'kind', 'metadata', 'spec'],
    'private infrastructure binding',
  );

  assertRecord(value.metadata, 'private infrastructure binding metadata');
  assertExactKeys(value.metadata, ['id'], 'private infrastructure binding metadata');
  assertRecord(value.spec, 'private infrastructure binding spec');
  assertExactKeys(
    value.spec,
    ['producer', 'consumer', 'contract', 'payload'],
    'private infrastructure binding spec',
  );
  assertRecord(value.spec.producer, 'private infrastructure binding producer');
  assertRecord(value.spec.consumer, 'private infrastructure binding consumer');
  assertRecord(value.spec.contract, 'private infrastructure binding contract');

  if (
    value.apiVersion !== 'pds/v1alpha1' ||
    value.kind !== 'RuntimeBinding' ||
    value.metadata.id !== 'digital-biome-private-infrastructure-v1' ||
    value.spec.producer.ref !== 'pds://system/component/personal-infrastructure' ||
    value.spec.consumer.ref !== 'pds://system/component/digital-biome' ||
    value.spec.contract.name !== 'digital-biome-private-infrastructure' ||
    value.spec.contract.version !== 'v1'
  ) {
    throw new Error('private infrastructure binding identity mismatch');
  }

  return parsePrivateInfrastructure(JSON.stringify(value.spec.payload));
}

function parseArgs(argv: string[]) {
  let contractPath =
    process.env.PDS_PRIVATE_INFRASTRUCTURE_BINDING?.trim() ||
    DEFAULT_PRIVATE_INFRASTRUCTURE_BINDING;
  let outPath: string | null = null;
  let printOnly = false;
  let asDevVars = false;

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (token === '--') continue;
    if (token === '--contract') {
      const value = argv[index + 1];
      if (!value) throw new Error('--contract requires a value');
      contractPath = value;
      index += 1;
      continue;
    }
    if (token === '--out') {
      const value = argv[index + 1];
      if (!value) throw new Error('--out requires a value');
      outPath = value;
      index += 1;
      continue;
    }
    if (token === '--print') {
      printOnly = true;
      continue;
    }
    if (token === '--dev-vars') {
      asDevVars = true;
      continue;
    }
    throw new Error(`unknown argument: ${token}`);
  }

  return { contractPath: path.resolve(contractPath), outPath, printOnly, asDevVars };
}

function loadBinding(contractPath: string): PrivateInfrastructurePayload {
  if (!fs.existsSync(contractPath)) {
    throw new Error(
      `Private infrastructure binding not found at ${contractPath}. ` +
        'Materialize the pinned Personal Infrastructure contract or pass --contract.',
    );
  }
  return parsePrivateInfrastructureBinding(fs.readFileSync(contractPath, 'utf8'));
}

function main() {
  const { contractPath, outPath, printOnly, asDevVars } = parseArgs(process.argv.slice(2));
  const payload = loadBinding(contractPath);
  const json = JSON.stringify(payload);
  const pretty = JSON.stringify(payload, null, 2);

  if (printOnly) {
    process.stdout.write(`${pretty}\n`);
    return;
  }

  if (asDevVars) {
    const content = [
      '# Generated by pnpm export:private -- --contract <binding> --dev-vars',
      '# Fill CF_ACCESS_* for local Pages Functions emulation with wrangler pages dev.',
      'CF_ACCESS_TEAM_DOMAIN=example.cloudflareaccess.com',
      'CF_ACCESS_AUD=0000000000000000000000000000000000000000000000000000000000000000',
      `PRIVATE_INFRASTRUCTURE_JSON=${json}`,
      '',
    ].join('\n');
    const target = outPath || '.dev.vars';
    fs.writeFileSync(target, content, 'utf8');
    console.log(
      `Wrote ${target} (${Object.keys(payload.values).length} values, ${Object.keys(payload.links).length} links)`,
    );
    return;
  }

  const target = outPath || path.join('tmp', 'private-infrastructure.json');
  fs.mkdirSync(path.dirname(path.resolve(target)), { recursive: true });
  fs.writeFileSync(target, `${pretty}\n`, 'utf8');
  console.log(
    `Wrote ${target} (${Object.keys(payload.values).length} values, ${Object.keys(payload.links).length} links)`,
  );
  console.log(
    'Set Cloudflare secret PRIVATE_INFRASTRUCTURE_JSON to the rendered JSON (or use the file contents).',
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main();
}
