/**
 * Export PRIVATE_INFRASTRUCTURE_JSON from upstream asset-index.
 *
 * Usage:
 *   pnpm export:private
 *   pnpm export:private -- --out .dev.vars.private.json
 *   pnpm export:private -- --print
 *
 * Values are derived from protected asset links. Host IPs are accepted only
 * from an explicit protected SSH link, never from the first arbitrary URL.
 */
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { notesConfig } from '../notes.config';
import { buildPrivateLinkRefs } from '../edge/private-refs';
import { parsePrivateInfrastructure } from '../edge/private-infrastructure';

interface UpstreamAssetLink {
  label: string;
  url: string;
  kind?: string;
  visibility?: 'public' | 'private' | 'internal';
}

interface UpstreamAssetItem {
  assetId: string;
  assetType?: string;
  links?: UpstreamAssetLink[];
}

const IPV4_HOSTNAME =
  /^(?:25[0-5]|2[0-4]\d|1?\d?\d)(?:\.(?:25[0-5]|2[0-4]\d|1?\d?\d)){3}$/;

const REQUIRED_SHOWCASE_HOSTS = [
  'host-azure-hk-vps',
  'host-aliyun-chengdu-dailyuse-vps',
  'host-azure-japan-singbox-vps',
  'host-azure-korea-singbox-vps',
] as const;

function extractSshHostnameIp(url: string): string | null {
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== 'ssh:') return null;
    if (IPV4_HOSTNAME.test(parsed.hostname)) {
      return parsed.hostname;
    }
  } catch {
    // ignore invalid URLs
  }
  return null;
}

function loadUpstreamAssets(): UpstreamAssetItem[] {
  const upstreamPath = path.resolve(
    process.cwd(),
    notesConfig.upstream.generatedPath,
    'knowledge-index',
    'asset-index.json',
  );
  if (!fs.existsSync(upstreamPath)) {
    throw new Error(
      `Upstream asset-index not found at ${upstreamPath}. Run kb:index in thought-forest or set NOTES_UPSTREAM_GENERATED.`,
    );
  }
  const parsed: unknown = JSON.parse(fs.readFileSync(upstreamPath, 'utf8'));
  if (!Array.isArray(parsed)) {
    throw new Error('Upstream asset-index must be an array.');
  }
  return parsed as UpstreamAssetItem[];
}

export function buildPrivateInfrastructurePayload(assets: UpstreamAssetItem[]) {
  const values: Record<string, string> = {};
  const links: Record<string, string> = {};
  const sshIpsByAsset = new Map<string, Set<string>>();

  for (const asset of assets) {
    const assetLinks = asset.links ?? [];
    for (const { link, privateRef } of buildPrivateLinkRefs(asset.assetId, assetLinks)) {
      if (!privateRef || !link.url) continue;
      links[privateRef] = link.url.trim();
      if (link.kind === 'ssh') {
        const ip = extractSshHostnameIp(link.url);
        if (!ip) {
          throw new Error(`${asset.assetId} has a protected SSH link without an IPv4 hostname.`);
        }
        const ips = sshIpsByAsset.get(asset.assetId) ?? new Set<string>();
        ips.add(ip);
        sshIpsByAsset.set(asset.assetId, ips);
      }
    }
  }

  for (const [assetId, ips] of sshIpsByAsset) {
    if (ips.size !== 1) {
      throw new Error(`${assetId} must resolve to exactly one IP from protected SSH links.`);
    }
    values[`${assetId}.ip`] = [...ips][0];
  }

  for (const assetId of REQUIRED_SHOWCASE_HOSTS) {
    if (!values[`${assetId}.ip`]) {
      throw new Error(`${assetId} must define exactly one protected SSH IPv4 link.`);
    }
  }

  return {
    version: 1 as const,
    values,
    links,
  };
}

function parseArgs(argv: string[]) {
  const outIndex = argv.indexOf('--out');
  const outPath = outIndex >= 0 ? argv[outIndex + 1] : null;
  const printOnly = argv.includes('--print');
  const asDevVars = argv.includes('--dev-vars');
  return { outPath, printOnly, asDevVars };
}

function main() {
  const { outPath, printOnly, asDevVars } = parseArgs(process.argv.slice(2));
  const payload = buildPrivateInfrastructurePayload(loadUpstreamAssets());
  // Validate against runtime parser before writing.
  parsePrivateInfrastructure(JSON.stringify(payload));

  const json = JSON.stringify(payload);
  const pretty = JSON.stringify(payload, null, 2);

  if (printOnly) {
    process.stdout.write(`${pretty}\n`);
    return;
  }

  if (asDevVars) {
    const content = [
      '# Generated by pnpm export:private -- --dev-vars',
      '# Fill CF_ACCESS_* for local Pages Functions emulation with wrangler pages dev.',
      'CF_ACCESS_TEAM_DOMAIN=example.cloudflareaccess.com',
      'CF_ACCESS_AUD=0000000000000000000000000000000000000000000000000000000000000000',
      `PRIVATE_INFRASTRUCTURE_JSON=${json}`,
      '',
    ].join('\n');
    const target = outPath || '.dev.vars';
    fs.writeFileSync(target, content, 'utf8');
    console.log(`Wrote ${target} (${Object.keys(payload.values).length} values, ${Object.keys(payload.links).length} links)`);
    return;
  }

  const target = outPath || path.join('tmp', 'private-infrastructure.json');
  fs.mkdirSync(path.dirname(path.resolve(target)), { recursive: true });
  fs.writeFileSync(target, `${pretty}\n`, 'utf8');
  console.log(`Wrote ${target} (${Object.keys(payload.values).length} values, ${Object.keys(payload.links).length} links)`);
  console.log('Set Cloudflare secret PRIVATE_INFRASTRUCTURE_JSON to the minified JSON (or use the file contents).');
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main();
}
